name: Backwards

on:
  push:
    branches:
      - main
    paths:
      - 'Backwards/**'
      - '!.vs/**'
      - '.github/**'
  pull_request:
    branches:
      - main

jobs:
  _build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - name: Hol vagyok?
      run: C:\actions-runner\whereami.bat
    - uses: actions/checkout@v3
    - name: .NET Előkészítése
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: Függőségek visszaállítása
      run: dotnet restore
    - name: Építés
      run: dotnet build -c Release --no-restore
    - name: Tesztelés
      run: dotnet test --no-build -c Release --verbosity normal
    - name: Elkészült fájlok feltöltése
      uses: actions/upload-artifact@v3
      with:
        name: Frissen csomagolt építés
        path: C:\actions-runner\_work\Backwards\Backwards\Backwards\bin\Release\netcoreapp3.1\**
        retention-days: 10
        if-no-files-found: error
    - name: Új kiadás tervezése
      uses: release-drafter/release-drafter@v5
      with:
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
