# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  epites:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: .NET Előkészítése
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: Függőségek visszaállítása
      run: dotnet restore
    - name: Építés
      run: dotnet build --no-restore
    - name: Tesztelés
      run: dotnet test --no-build --verbosity normal
